using System.Collections.Generic;
using UnityEngine;

public class PlayerOutfits : MonoBehaviour
{
    public bool isPlayer1 = true;
    public GameObject outfits;
    
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        Vector3 newPosition = outfits.transform.localPosition;
        //newPosition.z = PlayerScript.isFacingRight ? 0.25f : -0.25f;
        outfits.transform.localPosition = newPosition;
    }

    private List<GameObject> AllChilds(GameObject root)
    {
        List<GameObject> result = new List<GameObject>();
        if (root.transform.childCount > 0)
        {
            foreach (Transform VARIABLE in root.transform)
            {
                Searcher(result, VARIABLE.gameObject);
            }
        }
        return result;
    }

    private void Searcher(List<GameObject> list, GameObject root)
    {
        list.Add(root);
        if (root.transform.childCount > 0)
        {
            foreach (Transform VARIABLE in root.transform)
            {
                Searcher(list, VARIABLE.gameObject);
            }
        }
    }
}
